auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: niliang.com
url: http://niliang107.github.io
feed: /atom.xml
author_info: <a href="http://niliang107.github.io">niliang</a>
